# Generated by Django 4.2.3 on 2023-07-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('sueldo_base', models.FloatField()),
                ('horas_trabajadas', models.DateTimeField(auto_now=True)),
                ('telefono', models.CharField(max_length=14)),
            ],
        ),
    ]
